import { Platform, StyleSheet } from 'react-native';

/**
 * Seapoint design tokens — mirrors the web app's indigo brand on a soft
 * lavender canvas with lifted white cards.
 */
export const palette = {
  brand: '#5a51e0',
  brandPressed: '#4840c4',
  brandSoft: '#ecebfb',
  brandDisabled: '#bcb8ef',
  canvas: '#eef0fb',
  surface: '#ffffff',
  inputFill: '#f5f6fc',
  inputBorder: '#daddef',
  cardBorder: '#ebedf6',
  textStrong: '#1b1a2e',
  textBody: '#43425c',
  textMuted: '#7c7c93',
  textFaint: '#9b9bb0',
};

const cardShadow = Platform.select({
  ios: {
    shadowColor: '#3b3590',
    shadowOpacity: 0.1,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  android: { elevation: 3 },
  default: {},
});

const buttonShadow = Platform.select({
  ios: {
    shadowColor: palette.brand,
    shadowOpacity: 0.32,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
  },
  android: { elevation: 4 },
  default: {},
});

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: palette.canvas },
  keyboard: { flex: 1 },
  scroll: { flexGrow: 1, paddingHorizontal: 20 },
  topBlur: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    zIndex: 10,
  },
  pageHeader: {
    height: 56,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pageHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    color: palette.textStrong,
    fontSize: 20,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  headerBackButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBackButtonPlaceholder: {
    width: 44,
    height: 44,
  },
  headerBackText: {
    color: palette.brand,
    fontSize: 34,
    lineHeight: 38,
  },
  subtitle: {
    fontSize: 15,
    color: palette.textMuted,
    marginBottom: 24,
    lineHeight: 21,
  },
  field: { marginBottom: 16 },
  label: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    color: palette.textBody,
  },
  input: {
    backgroundColor: palette.inputFill,
    borderWidth: 1,
    borderColor: palette.inputBorder,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 13,
    fontSize: 16,
    minHeight: 52,
    color: palette.textStrong,
  },
  inputFocused: {
    backgroundColor: palette.surface,
    borderColor: palette.brand,
  },
  inputMultiline: {
    minHeight: 52,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: palette.brand,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 54,
    marginTop: 8,
    ...buttonShadow,
  },
  buttonDisabled: { backgroundColor: palette.brandDisabled, ...Platform.select({ ios: { shadowOpacity: 0 }, default: {} }) },
  buttonPressed: { backgroundColor: palette.brandPressed },
  pressedFade: { opacity: 0.6 },
  loadingContent: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '700', letterSpacing: 0.2 },
  errorBox: {
    marginTop: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
    borderRadius: 12,
  },
  errorText: { color: '#b91c1c' },
  warningBox: {
    marginBottom: 16,
    padding: 14,
    borderWidth: 1,
    borderColor: '#fcd34d',
    backgroundColor: '#fffbeb',
    borderRadius: 12,
    gap: 6,
  },
  warningTitle: {
    color: '#92400e',
    fontSize: 14,
    fontWeight: '700',
  },
  warningText: {
    color: '#78350f',
    fontSize: 13,
    lineHeight: 18,
  },
  reviewList: { gap: 14, marginBottom: 16 },
  reviewField: {
    backgroundColor: palette.surface,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    ...cardShadow,
  },
  reviewFieldGroup: {
    backgroundColor: palette.surface,
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    gap: 12,
    ...cardShadow,
  },
  groupedReviewFields: { gap: 12 },
  groupedReviewField: {
    gap: 0,
  },
  reviewFieldError: {
    borderColor: '#ef4444',
  },
  fieldErrorText: {
    color: '#dc2626',
    fontSize: 12,
    marginTop: 4,
  },
  reviewFieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 8,
  },
  confidenceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  confidencePillHigh: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: palette.brandSoft,
  },
  confidencePillMedium: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#fef3c7',
  },
  confidencePillLow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#fee2e2',
  },
  confidenceMeter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  confidenceDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  confidenceDotHighActive: {
    backgroundColor: palette.brand,
  },
  confidenceDotMediumActive: {
    backgroundColor: '#d97706',
  },
  confidenceDotLowActive: {
    backgroundColor: '#dc2626',
  },
  confidenceDotInactive: {
    backgroundColor: '#e5e7eb',
  },
  confidenceLabelHigh: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.brand,
  },
  confidenceLabelMedium: {
    fontSize: 12,
    fontWeight: '700',
    color: '#92400e',
  },
  confidenceLabelLow: {
    fontSize: 12,
    fontWeight: '700',
    color: '#991b1b',
  },
  metadataRow: { marginTop: 10, gap: 4 },
  metadataText: { color: palette.textBody, fontSize: 12 },
  reasonText: { color: palette.textFaint, fontSize: 12, lineHeight: 17, fontStyle: 'italic' },
  confirmSection: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    borderRadius: 16,
    padding: 16,
    marginBottom: 14,
    ...cardShadow,
  },
  confirmSectionTitle: {
    color: palette.textStrong,
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
  },
  confirmRow: {
    borderTopWidth: 1,
    borderTopColor: '#f0f1f3',
    paddingTop: 10,
    marginTop: 10,
    gap: 4,
  },
  confirmLabel: {
    color: palette.textMuted,
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  confirmValue: {
    color: palette.textStrong,
    fontSize: 15,
    lineHeight: 21,
  },
  confirmValueEmpty: {
    color: palette.textFaint,
    fontSize: 14,
    lineHeight: 21,
    fontStyle: 'italic',
  },
  successPanel: {
    backgroundColor: palette.surface,
    borderWidth: 1,
    borderColor: palette.cardBorder,
    borderRadius: 16,
    padding: 24,
    alignItems: 'center',
    marginBottom: 16,
    ...cardShadow,
  },
  successIconHalo: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: palette.brandSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  successIcon: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: palette.brand,
    alignItems: 'center',
    justifyContent: 'center',
    ...buttonShadow,
  },
  successCheck: {
    color: '#fff',
    fontSize: 30,
    lineHeight: 34,
    fontWeight: '800',
  },
  successTitle: {
    color: palette.textStrong,
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  successText: {
    color: palette.textBody,
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'center',
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: palette.inputBorder,
    borderRadius: 12,
    paddingVertical: 15,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 54,
    backgroundColor: palette.surface,
  },
  secondaryButtonText: {
    color: palette.brand,
    fontSize: 16,
    fontWeight: '700',
  },
  datePickerTrigger: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  datePickerValue: {
    fontSize: 16,
    color: palette.textStrong,
    flex: 1,
  },
  datePickerPlaceholder: {
    fontSize: 16,
    color: palette.textFaint,
    flex: 1,
  },
  datePickerChevron: {
    fontSize: 20,
    color: palette.textFaint,
    lineHeight: 24,
    transform: [{ rotate: '90deg' }],
  },
  datePickerSpinner: {
    width: '100%',
  },
  dateModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(27,26,46,0.4)',
    justifyContent: 'flex-end',
  },
  dateModalSheet: {
    backgroundColor: palette.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingBottom: 32,
  },
  dateModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f1f3',
  },
  dateModalCancel: {
    fontSize: 16,
    color: palette.textMuted,
  },
  dateModalDone: {
    fontSize: 16,
    fontWeight: '700',
    color: palette.brand,
  },
});
