import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f7f7f8' },
  keyboard: { flex: 1 },
  scroll: { flexGrow: 1, paddingHorizontal: 20 },
  topBlur: {
    position: 'absolute',
    top: 0,
    right: 0,
    left: 0,
    zIndex: 10,
  },
  pageHeader: {
    height: 56,
    paddingHorizontal: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  pageHeaderTitle: {
    flex: 1,
    textAlign: 'center',
    color: '#111',
    fontSize: 20,
    fontWeight: '700',
  },
  headerBackButton: {
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBackButtonPlaceholder: {
    width: 44,
    height: 44,
  },
  headerBackText: {
    color: '#111',
    fontSize: 34,
    lineHeight: 38,
  },
  subtitle: { fontSize: 15, color: '#555', marginBottom: 24 },
  field: { marginBottom: 16 },
  label: { fontSize: 14, fontWeight: '500', marginBottom: 6, color: '#333' },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d6d6db',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    minHeight: 50,
  },
  inputMultiline: {
    minHeight: 50,
    textAlignVertical: 'top',
  },
  button: {
    backgroundColor: '#2563eb',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    marginTop: 8,
  },
  buttonDisabled: { backgroundColor: '#9bb6f0' },
  buttonPressed: { opacity: 0.85 },
  loadingContent: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  errorBox: {
    marginTop: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
    borderRadius: 10,
  },
  errorText: { color: '#b91c1c' },
  warningBox: {
    marginBottom: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#fcd34d',
    backgroundColor: '#fffbeb',
    borderRadius: 8,
    gap: 6,
  },
  warningTitle: {
    color: '#92400e',
    fontSize: 14,
    fontWeight: '700',
  },
  warningText: {
    color: '#78350f',
    fontSize: 13,
    lineHeight: 18,
  },
  reviewList: { gap: 12, marginBottom: 16 },
  reviewField: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  reviewFieldGroup: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    gap: 10,
  },
  groupedReviewFields: { gap: 12 },
  groupedReviewField: {
    gap: 0,
  },
  reviewFieldError: {
    borderColor: '#ef4444',
  },
  fieldErrorText: {
    color: '#dc2626',
    fontSize: 12,
    marginTop: 4,
  },
  reviewFieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 6,
  },
  confidenceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  confidencePillMedium: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#fef3c7',
  },
  confidencePillLow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
    backgroundColor: '#fee2e2',
  },
  confidenceMeter: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  confidenceDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
  },
  confidenceDotHighActive: {
    backgroundColor: '#9ca3af',
  },
  confidenceDotMediumActive: {
    backgroundColor: '#d97706',
  },
  confidenceDotLowActive: {
    backgroundColor: '#dc2626',
  },
  confidenceDotInactive: {
    backgroundColor: '#e5e7eb',
  },
  confidenceLabelHigh: {
    fontSize: 12,
    fontWeight: '500',
    color: '#9ca3af',
  },
  confidenceLabelMedium: {
    fontSize: 12,
    fontWeight: '700',
    color: '#92400e',
  },
  confidenceLabelLow: {
    fontSize: 12,
    fontWeight: '700',
    color: '#991b1b',
  },
  metadataRow: { marginTop: 8, gap: 4 },
  metadataText: { color: '#4b5563', fontSize: 12 },
  reasonText: { color: '#6b7280', fontSize: 12, lineHeight: 17 },
  confirmSection: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    padding: 14,
    marginBottom: 14,
  },
  confirmSectionTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
  },
  confirmRow: {
    borderTopWidth: 1,
    borderTopColor: '#f0f1f3',
    paddingTop: 10,
    marginTop: 10,
    gap: 4,
  },
  confirmLabel: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  confirmValue: {
    color: '#111827',
    fontSize: 15,
    lineHeight: 21,
  },
  confirmValueEmpty: {
    color: '#9ca3af',
    fontSize: 14,
    lineHeight: 21,
    fontStyle: 'italic',
  },
  successPanel: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#bbf7d0',
    borderRadius: 8,
    padding: 20,
    alignItems: 'center',
    marginBottom: 16,
  },
  successIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    overflow: 'hidden',
    backgroundColor: '#16a34a',
    color: '#fff',
    fontSize: 14,
    lineHeight: 40,
    fontWeight: '800',
    textAlign: 'center',
    marginBottom: 12,
  },
  successTitle: {
    color: '#111827',
    fontSize: 20,
    fontWeight: '800',
    marginBottom: 8,
    textAlign: 'center',
  },
  successText: {
    color: '#4b5563',
    fontSize: 15,
    lineHeight: 21,
    textAlign: 'center',
  },
  secondaryButton: {
    borderWidth: 1,
    borderColor: '#c7ccd5',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    backgroundColor: '#fff',
  },
  secondaryButtonText: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '600',
  },
});
