import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#f7f7f8' },
  keyboard: { flex: 1 },
  scroll: { flexGrow: 1, padding: 20, paddingTop: 32, paddingBottom: 40 },
  h1: { fontSize: 28, fontWeight: '700', marginBottom: 8, color: '#111' },
  subtitle: { fontSize: 15, color: '#555', marginBottom: 24 },
  field: { marginBottom: 16 },
  label: { fontSize: 14, fontWeight: '500', marginBottom: 6, color: '#333' },
  input: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#d6d6db',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
    minHeight: 50,
  },
  button: {
    backgroundColor: '#2563eb',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 52,
    marginTop: 8,
  },
  buttonDisabled: { backgroundColor: '#9bb6f0' },
  buttonPressed: { opacity: 0.85 },
  loadingContent: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  buttonText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  errorBox: {
    marginTop: 16,
    padding: 12,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
    borderRadius: 10,
  },
  errorText: { color: '#b91c1c' },
  reviewList: { gap: 12, marginBottom: 16 },
  reviewField: {
    backgroundColor: '#fff',
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  lowConfidence: {
    borderColor: '#f59e0b',
    backgroundColor: '#fffbeb',
  },
  reviewFieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 6,
  },
  confidenceBadge: {
    overflow: 'hidden',
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: '#eef2ff',
    color: '#3730a3',
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'capitalize',
  },
  lowConfidenceBadge: {
    backgroundColor: '#fef3c7',
    color: '#92400e',
  },
  metadataRow: { marginTop: 8, gap: 4 },
  metadataText: { color: '#4b5563', fontSize: 12 },
  reasonText: { color: '#6b7280', fontSize: 12, lineHeight: 17 },
  confirmBox: { paddingTop: 80, alignItems: 'center' },
});
